// Auto-generated by generate_aos_mappings.py
#include "interpreter.h"

void init_command_map() {
  add_command("HELLO", cmd_hello_wrapper);
  add_command("BYE", cmd_bye_wrapper);
  add_command("UI_GRAPH", cmd_ui_graph_wrapper);
  add_command("MEM_ALLOC", cmd_mem_alloc_wrapper);
  add_command("MEM_FREE", cmd_mem_free_wrapper);
  add_command("FS_OPEN", cmd_fs_open_wrapper);
  add_command("FS_WRITE", cmd_fs_write_wrapper);
  add_command("FS_READ", cmd_fs_read_wrapper);
  add_command("FS_CLOSE", cmd_fs_close_wrapper);
  add_command("FS_LS", cmd_fs_ls_wrapper);
  add_command("AI_PROMPT", cmd_ai_prompt_wrapper);
  add_command("AI_PROFILE", cmd_ai_profile_wrapper);
  add_command("BR_CREATE", cmd_br_create_wrapper);
  add_command("BR_LIST", cmd_br_list_wrapper);
  add_command("BR_STOP", cmd_br_stop_wrapper);
  add_command("BR_DELETE", cmd_br_delete_wrapper);
  add_command("BR_VM_CREATE", cmd_br_vm_create_wrapper);
  add_command("BR_VM_LIST", cmd_br_vm_list_wrapper);
  add_command("BR_VM_SWITCH", cmd_br_vm_switch_wrapper);
  add_command("BR_VM_STOP", cmd_br_vm_stop_wrapper);
  add_command("PLUGIN_INSTALL", cmd_plugin_install_wrapper);
  add_command("PLUGIN_LIST", cmd_plugin_list_wrapper);
  add_command("PLUGIN_LOAD", cmd_plugin_load_wrapper);
  add_command("BR_PEER_ADD", cmd_br_peer_add_wrapper);
  add_command("BR_SYNC", cmd_br_sync_wrapper);
  add_command("BR_SYNC_ALL", cmd_br_sync_all_wrapper);
  add_command("AI_SERVICE_CREATE", cmd_ai_service_create_wrapper);
  add_command("AI_SERVICE_MONITOR", cmd_ai_service_monitor_wrapper);
  add_command("POLICY_LOAD", cmd_policy_load_wrapper);
  add_command("POLICY_CHECK", cmd_policy_check_wrapper);
}
