FROM ubuntu:24.04

RUN apt-get update && \
    apt-get install -y build-essential clang python3.11 python3.11-venv python3-pip nodejs npm

WORKDIR /aos
COPY . .

RUN pip install -r requirements.txt

# run quick tests only
RUN make fast-test

CMD ["bash"]
