apiVersion: apps/v1
kind: Deployment
metadata:
  name: aos-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aos-api
  template:
    metadata:
      labels:
        app: aos-api
    spec:
      containers:
      - name: api
        image: aos-api:latest
        ports:
        - containerPort: 8000
        readinessProbe:
          httpGet:
            path: /health/ready
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /health/live
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 10
