apiVersion: apps/v1
kind: Deployment
metadata:
  name: aos-worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aos-worker
  template:
    metadata:
      labels:
        app: aos-worker
    spec:
      containers:
      - name: worker
        image: aos-worker:latest
        command: ["python", "scripts/jobqueue/worker.py"]
        readinessProbe:
          httpGet:
            path: /health/ready
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /health/live
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 10
