// Auto-generated category IDs
#ifndef CATEGORY_DEFS_H
#define CATEGORY_DEFS_H

#define CAT_BASIC_SYSTEM_COMMANDS 0x01
#define CAT_TIMERS 0x02
#define CAT_PROCESSES 0x03
#define CAT_FILE_OPERATIONS 0x04
#define CAT_NETWORKING 0x05
#define CAT_SYSTEM_ACTIONS 0x06
#define CAT_USER_MANAGEMENT 0x07
#define CAT_SECURITY 0x08
#define CAT_APPLICATION_CONTROL 0x09
#define CAT_SYSTEM_MONITORING 0x0A
#define CAT_SCHEDULING 0x0B
#define CAT_BACKUP___RESTORE 0x0C
#define CAT_POWER_MANAGEMENT 0x0D
#define CAT_ACCESSIBILITY 0x0E
#define CAT_LOCALIZATION 0x0F
#define CAT_DEVELOPMENT___DEBUGGING 0x10
#define CAT_HARDWARE_MANAGEMENT 0x11
#define CAT_PERIPHERAL_DEVICES 0x12
#define CAT_VIRTUALIZATION 0x13
#define CAT_PACKAGE_MANAGEMENT 0x14
#define CAT_ENVIRONMENT_VARIABLES 0x15
#define CAT_SYSTEM_LOGS 0x16
#define CAT_DISK_MANAGEMENT 0x17
#define CAT_ENCRYPTION 0x18
#define CAT_RESOURCE_MANAGEMENT 0x19
#define CAT_DEVICE_DRIVERS 0x1A
#define CAT_COMMAND_ALIASES 0x1B
#define CAT_SCRIPTING___AUTOMATION 0x1C
#define CAT_MISCELLANEOUS 0x1D
#define CAT_META_STATE_COMMANDS 0x1E
#define CAT_AI_INTEGRATION 0x1F
#define CAT_ERROR_RECOVERY 0x20
#define CAT_COMPRESSION 0x21
#define CAT_ADAPTIVE_ENCODING 0x22

#endif
