name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build host
        run: make host
      - name: Build bare metal
        run: make bare
      - name: Run under QEMU
        run: make run RUN_OPTS="-nographic"
      - name: Check serial output
        run: |
          make run RUN_OPTS="-nographic" | tee output.log
          grep -q "Kernel started" output.log
