name: ci

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: [x86_64, riscv64, arm]
    env:
      CC_TARGET: ${{ matrix.arch }}
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libncurses5-dev libncursesw5-dev pkg-config libcurl4-openssl-dev clang clang-tidy clang-format lcov qemu-system-x86 qemu-system-arm qemu-system-misc
      - name: Format check
        run: |
          files=$(git ls-files '*.c' '*.h')
          clang-format -n --Werror $files
      - name: Clang tidy
        run: clang-tidy $(git ls-files '*.c') -- -Iinclude
      - name: Validate mappings
        run: python3 generate_aos_mappings.py --validate
      - name: Build host
        run: make host
      - name: Run tests
        run: make test
      - name: Fuzz tests
        run: make test-fuzz
      - name: Coverage
        run: make coverage
      - name: QEMU smoke
        run: |
          make boot CC_TARGET=${{ matrix.arch }}
          ./scripts/qemu_smoke.sh ${{ matrix.arch }}
