name: ci

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libncurses5-dev libncursesw5-dev pkg-config libcurl4-openssl-dev
      - name: Build host and demos
        run: make host
      - name: Test memory
        run: ./build/memory_demo
      - name: Test fs
        run: ./build/fs_demo
      - name: Test ai
        run: echo "hello" | ./build/ai_demo
      - name: Test branch
        run: ./build/branch_demo
      - name: Test branch-vm
        run: make branch-vm && ./build/branch_vm_demo
      - name: Test plugins
        run: make plugins && ./build/plugin_demo
      - name: Test iso
        run: make iso && test -f aos.iso
      - name: Test branch-net
        run: make branch-net && ./build/branch_fed_demo
      - name: Test ai-service
        run: make ai-service && ./build/ai_service_demo
      - name: Test policy
        run: make policy && ./build/policy_demo
      - name: Test ui
        run: make ui-check
