name: ci

on: [push, pull_request]

jobs:
  clang-format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install clang-format
        run: sudo apt-get update && sudo apt-get install -y clang-format
      - name: format
        run: clang-format -n --Werror $(git ls-files '*.c' '*.h')

  clang-tidy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install clang-tidy
        run: sudo apt-get update && sudo apt-get install -y clang-tidy
      - name: Generate compilation database
        run: |
          pip install compiledb
          make regenerate
          compiledb -n make host
      - name: tidy
        run: clang-tidy -p compile_commands.json $(git ls-files '*.c') -- -Iinclude

  build:
    runs-on: ubuntu-latest
    needs: [clang-format, clang-tidy]
    steps:
      - uses: actions/checkout@v2
      - name: Install deps
        run: |
          sudo apt-get update
          sudo apt-get install -y libncurses5-dev libncursesw5-dev pkg-config libcurl4-openssl-dev clang lcov
          pip install pre-commit gcovr
      - name: pre-commit
        run: pre-commit run --files $(git ls-files '*.py' '*.c' '*.h' '*.yaml')
      - name: Build host
        run: make host
      - name: Unit tests
        run: make test-unit
      - name: Integration tests
        run: make test-integration
      - name: Coverage
        run: gcovr -r . --lcov -o coverage.lcov
      - name: Upload coverage
        uses: codecov/codecov-action@v3
        with:
          files: coverage.lcov
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: RedactedCoder23/AOS

  sanitize-build:
    runs-on: ubuntu-latest
    needs: [clang-format, clang-tidy]
    steps:
      - uses: actions/checkout@v2
      - name: Install deps
        run: sudo apt-get update && sudo apt-get install -y clang
      - name: Build with sanitizers
        run: CFLAGS='-fsanitize=address,undefined -g' make host
      - name: Unit tests with sanitizers
        run: CFLAGS='-fsanitize=address,undefined -g' make test-unit
      - name: Integration tests with sanitizers
        run: CFLAGS='-fsanitize=address,undefined -g' make test-integration
