name: CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # install system dependencies
      - name: Install deps
        run: sudo apt-get update && sudo apt-get install -y build-essential pkg-config python3

      - name: Build AOS
        run: make all

      - name: Run tests
        run: make test

  clang-format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Check formatting
        run: |
          find src include host subsystems -type f \( -name '*.c' -o -name '*.h' \) \
            -exec clang-format --dry-run --Werror {} +

  asan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build with ASan
        run: |
          make clean
          make CFLAGS="-g -O1 -fsanitize=address -fno-omit-frame-pointer"
          ./bin/aos-host --run-fuzz-tests
