name: ci

on: [push, pull_request]

jobs:
  fast:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - uses: actions/setup-node@v3
        with:
          node-version: '20'
      - name: Install deps
        run: pip install -r requirements.txt pre-commit
      - name: Run fast CI
        run: ./scripts/ci-fast.sh

