name: nightly

on:
  schedule:
    - cron: '0 0 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install deps
        run: |
          sudo apt-get update
          sudo apt-get install -y libncurses5-dev libncursesw5-dev pkg-config
      - name: Build and test
        run: |
          make host
          make test-unit
          make test-integration
