name: nightly

on:
  schedule:
    - cron: '0 0 * * *'

jobs:
  nightly:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - uses: actions/setup-node@v3
        with:
          node-version: '20'
      - name: Install deps
        run: pip install -r requirements.txt -r requirements-dev.txt pre-commit
      - name: Run full CI
        run: ./scripts/ci-full.sh
      - name: Set up buildx
        uses: docker/setup-buildx-action@v3
      - name: Cache Docker layers
        uses: actions/cache@v4
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-
      - name: Build dev container
        run: docker build -f Dockerfile.dev -t aos-dev:${{ github.sha }} .
      - name: Run pip-audit
        run: |
          pip install pip-audit
          pip-audit -r requirements.txt -r requirements-dev.txt
      - name: Run npm audit
        run: |
          cd ui
          npm install
          npm audit --audit-level=high --json
      - name: Start API server
        run: |
          uvicorn src.api.health:app --port 8000 --log-level warning &
          echo $! > uv.pid
          sleep 5
      - name: OWASP ZAP baseline
        uses: zaproxy/action-baseline@v0.12.0
        with:
          target: http://localhost:8000
          fail_action: true
      - name: Stop server
        run: kill $(cat uv.pid)

