name: ui

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Build UI
        run: |
          cd ui
          npm install
          npm run lint
          npm run build
      - name: Run UI checks
        run: make ui-check
